/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DownloadUrlService } from "../downloadUrl.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DownloadUrlCreateInput } from "./DownloadUrlCreateInput";
import { DownloadUrl } from "./DownloadUrl";
import { DownloadUrlFindManyArgs } from "./DownloadUrlFindManyArgs";
import { DownloadUrlWhereUniqueInput } from "./DownloadUrlWhereUniqueInput";
import { DownloadUrlUpdateInput } from "./DownloadUrlUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DownloadUrlControllerBase {
  constructor(
    protected readonly service: DownloadUrlService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DownloadUrl })
  @nestAccessControl.UseRoles({
    resource: "DownloadUrl",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDownloadUrl(
    @common.Body() data: DownloadUrlCreateInput
  ): Promise<DownloadUrl> {
    return await this.service.createDownloadUrl({
      data: {
        ...data,

        apiKey: data.apiKey
          ? {
              connect: data.apiKey,
            }
          : undefined,

        model: data.model
          ? {
              connect: data.model,
            }
          : undefined,
      },
      select: {
        apiKey: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiryDate: true,
        id: true,

        model: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DownloadUrl] })
  @ApiNestedQuery(DownloadUrlFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DownloadUrl",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async downloadUrls(@common.Req() request: Request): Promise<DownloadUrl[]> {
    const args = plainToClass(DownloadUrlFindManyArgs, request.query);
    return this.service.downloadUrls({
      ...args,
      select: {
        apiKey: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiryDate: true,
        id: true,

        model: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DownloadUrl })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadUrl",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async downloadUrl(
    @common.Param() params: DownloadUrlWhereUniqueInput
  ): Promise<DownloadUrl | null> {
    const result = await this.service.downloadUrl({
      where: params,
      select: {
        apiKey: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiryDate: true,
        id: true,

        model: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DownloadUrl })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadUrl",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDownloadUrl(
    @common.Param() params: DownloadUrlWhereUniqueInput,
    @common.Body() data: DownloadUrlUpdateInput
  ): Promise<DownloadUrl | null> {
    try {
      return await this.service.updateDownloadUrl({
        where: params,
        data: {
          ...data,

          apiKey: data.apiKey
            ? {
                connect: data.apiKey,
              }
            : undefined,

          model: data.model
            ? {
                connect: data.model,
              }
            : undefined,
        },
        select: {
          apiKey: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expiryDate: true,
          id: true,

          model: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DownloadUrl })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DownloadUrl",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDownloadUrl(
    @common.Param() params: DownloadUrlWhereUniqueInput
  ): Promise<DownloadUrl | null> {
    try {
      return await this.service.deleteDownloadUrl({
        where: params,
        select: {
          apiKey: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expiryDate: true,
          id: true,

          model: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
